dist: trusty
sudo: false
language: python
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
matrix:
  fast_finish: true
install:
    - pip install -r requirements-dev.txt
    - pip install -e .
script:
    - pytest
after_script:
    - pip install --quiet coveralls
    - coveralls
