dist: trusty
sudo: false
language: python
python:
    - 2.7
    - 3.5
matrix:
  allow_failures:
    - python: 3.5
  fast_finish: true
install:
    - pip install -r requirements-dev.txt
    - pip install -e .
script:
    - pytest
after_script:
    - pip install --quiet coveralls
    - coveralls
